name: Test Outer Empty String Input

on:
  workflow_dispatch:
    inputs:
      input-string:
        type: string
        default: default-value
        required: true
        description: |
          input-string to test if-condition in step-level

jobs:
  run-job-with-input:
    uses: IndritFejza/test-gha/.github/workflows/deploy-inner-test.yaml@main
    with:
      input-string: ${{ github.event.inputs.input-string }}
    permissions:
      contents: read
