name: Test Inner String Input

on:
  workflow_call:
    inputs:
      input-string:
        type: string
        default: default-value
        required: true
        description: |
          input-string to test if-condition in step-level
jobs:
  test-input-handling:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      INPUT_STRING: ${{ inputs.input-string }} 
    steps:
      - name: Tag Testrunner Image
        shell: bash
        run: |
          if [ -z "$INPUT_STRING" ]; then
            echo "INPUT_STRING is empty"
          else
            echo "INPUT_STRING is not empty"
          fi
                    
          echo "Running test with input: ${{ inputs.input-string }}"
          echo "Running test with input: $INPUT_STRING"
